os: osx
osx_image: xcode10.1
addons:
  homebrew:
    taps: AdoptOpenJDK/openjdk
    casks: adoptopenjdk15
    packages: 
    - create-dmg
    update: true

language: java

before_script:
  - export P12="CodeSigningCert.p12"
  - export KEYCHAIN="build.keychain"
  - echo $CODE_SIGN_CERT | base64 --decode > $P12
  - security create-keychain -p mysecretpassword $KEYCHAIN
  - security default-keychain -s $KEYCHAIN
  - security unlock-keychain -p mysecretpassword $KEYCHAIN
  - security set-keychain-settings $KEYCHAIN
  - security import $P12 -k $KEYCHAIN -P $CODE_SIGN_PWD -T /usr/bin/codesign
  - |-
    security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k mysecretpassword $KEYCHAIN

script:
  - export JAVA_HOME=$(/usr/libexec/java_home -v15);
  - cd kse
  - ./gradlew dmg

deploy:
  provider: releases
  api_key:
    secure: WnK8GtkON4G0LnVu38mJ6dZwmX1goMtjL5k9+1QpcG+K5zaox92s01NFpNjyNNdTSjKxavj0Lk2Qbl3lmll6aSfjra1qSoSk28uZNOTDxzZTGkimhWs8QpsiQGvmdU9RSobENyeqTb3epVRN1js1NRj+Jx3pFChTtAGpDrigVM7mbDPNOBEUt77L5JpNWDfrvzw4O1CoMzL+ztEG4lruj0tDh83qJUN7QbrtRX3skrq5qN3P4eDKUIsrX6Db9auCiO8wS4dz8+/g+IRsMDZP6bVINMKBkCVEWCLjL+L0+KNoEvl6JlocDtU7echDLrDfsn94SjoEu9+xMyR6AfW+7FAYJyOFkCT6UyH5+TnOAHokFNEL9opmjERnYN5myf0bjo0rJlSjBbJPjJq7FJD2f/9SMEcyy01jvktiMS84tlRRrGX+INwOUt7V1J/hU4KzbnJKtorEdy4evNKBfT44DzABpOvbpOdDgIi8c4BcKVW0l53VDv5DAWLGgmyjBmudyKkTtTrH2Wxd1IjD1NaIWiYkGNzv8ChlcLDiJSW6QldtFDKaQdKrBngRRuUpeHg2todMsLB3U6uS3fC3oPQiy8sLkv85SZ5beT695FOHorixfkjps56SJbc2cF9bK6jBHnNgy1XaF0q1nIO4NmGLiwOyMcgu10n7mCd5dhhuj0k=
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/kse/build/distributions/kse-*.dmg
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT  
  draft: true
  overwrite: true
  on:
    tags: true